import React from "react";
const columns = [
    { name: "ID", uid: "id", sortable: true },
    { name: "BANNER", uid: "banner" },
    { name: "TITLE", uid: "title", sortable: true },
    { name: "ORGANIZER", uid: "organizer", sortable: true },
    { name: "DATE", uid: "date", sortable: true },
    { name: "LOCATION", uid: "location", sortable: true },
    { name: "ATTENDEES", uid: "attendees", sortable: true },
    { name: "STATUS", uid: "status", sortable: true },
    { name: "CONTACT EMAIL", uid: "contactEmail" },
    { name: "ACTIONS", uid: "actions" },
  ];

const statusOptions = [
    { name: "Upcoming", uid: "upcoming" },
    { name: "Ongoing", uid: "ongoing" },
    { name: "Completed", uid: "completed" },
    { name: "Cancelled", uid: "cancelled" },
  ];
  

const conferences = [
    {
      id: 1,
      title: "Global Tech Summit 2024",
      organizer: "Tech Corp",
      date: "2024-03-15",
      location: "San Francisco, CA",
      status: "ongoing",
      attendees: 5000,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@globaltechsummit.com",
    },
    {
      id: 2,
      title: "AI & Machine Learning Conference",
      organizer: "AI World",
      date: "2024-05-22",
      location: "New York, NY",
      status: "ongoing",
      attendees: 3200,
      banner: "https://www.am.ai/static/caeb54cb7ba4bcb78cf209724f43cb3d/8c557/logo_icml.png",
      contactEmail: "info@aimlconference.com",
    },
    {
      id: 3,
      title: "Web Development Expo",
      organizer: "WebDev Innovators",
      date: "2024-07-10",
      location: "Los Angeles, CA",
      status: "ongoing",
      attendees: 4500,
      banner: "https://aiconference.co.ke/assets/landscape-lCvpOyXa.webp",
      contactEmail: "info@webdevexpo.com",
    },
    {
      id: 4,
      title: "Marketing Trends 2024",
      organizer: "Marketers United",
      date: "2024-02-20",
      location: "London, UK",
      status: "ongoing",
      attendees: 3500,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@marketingtrends2024.com",
    },
    {
      id: 5,
      title: "Cloud Computing Forum",
      organizer: "CloudX",
      date: "2024-09-05",
      location: "Berlin, Germany",
      status: "completed",
      attendees: 4000,
      banner: "https://aiconference.co.ke/assets/landscape-lCvpOyXa.webp",
      contactEmail: "info@cloudcomputingforum.com",
    },
    {
      id: 6,
      title: "Cybersecurity Symposium",
      organizer: "SecOps Global",
      date: "2024-11-12",
      location: "Singapore",
      status: "completed",
      attendees: 3800,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@cybersecuritysymposium.com",
    },
    {
      id: 7,
      title: "Blockchain Innovations Conference",
      organizer: "CryptoWorld",
      date: "2024-06-18",
      location: "Dubai, UAE",
      status: "completed",
      attendees: 4200,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@blockchainconference.com",
    },
    {
      id: 8,
      title: "Human Resources Summit",
      organizer: "HR Connect",
      date: "2024-10-30",
      location: "Sydney, Australia",
      status: "cancelled",
      attendees: 3300,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@hrsummit.com",
    },
    {
      id: 9,
      title: "Fintech Innovations Expo",
      organizer: "Fintech Innovators",
      date: "2024-08-20",
      location: "Toronto, Canada",
      status: "cancelled",
      attendees: 3600,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@fintechexpo.com",
    },
    {
      id: 10,
      title: "Healthcare Technology Forum",
      organizer: "HealthTech Global",
      date: "2024-12-05",
      location: "Amsterdam, Netherlands",
      status: "cancelled",
      attendees: 2700,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@healthtechforum.com",
    },
    {
      id: 11,
      title: "Startup World Summit",
      organizer: "Startup Innovators",
      date: "2024-04-12",
      location: "Silicon Valley, CA",
      status: "cancelled",
      attendees: 3000,
      banner: "https://opencv.org/wp-content/uploads/2019/04/CVPR2019LogoCrop.png",
      contactEmail: "info@startupworldsummit.com",
    },
    {
      id: 12,
      title: "Digital Transformation Conference",
      organizer: "DigiTrans Global",
      date: "2024-11-25",
      location: "Tokyo, Japan",
      status: "upcoming",
      attendees: 3900,
      banner: "https://ife.no/wp-content/uploads/2022/11/icapai-logo-2023.gif",
      contactEmail: "info@digitransconference.com",
    },
    {
      id: 13,
      title: "Sustainability & Green Tech Expo",
      organizer: "GreenTech Innovators",
      date: "2024-06-05",
      location: "Paris, France",
      status: "upcoming",
      attendees: 2500,
      banner: "https://ife.no/wp-content/uploads/2022/11/icapai-logo-2023.gif",
      contactEmail: "info@greentechexpo.com",
    },
    {
      id: 14,
      title: "Gaming & Esports Convention",
      organizer: "GameX",
      date: "2024-09-18",
      location: "Seoul, South Korea",
      status: "upcoming",
      attendees: 5500,
      banner: "https://ife.no/wp-content/uploads/2022/11/icapai-logo-2023.gif",
      contactEmail: "info@gamingesportscon.com",
    },
    {
      id: 15,
      title: "VR & AR Innovations Summit",
      organizer: "VRTech",
      date: "2024-07-22",
      location: "Austin, TX",
      status: "upcoming",
      attendees: 2900,
      banner: "https://ife.no/wp-content/uploads/2022/11/icapai-logo-2023.gif",
      contactEmail: "info@vrarinnovations.com",
    },
    {
      id: 16,
      title: "Renewable Energy Conference",
      organizer: "EcoEnergy Global",
      date: "2024-08-10",
      location: "Munich, Germany",
      status: "upcoming",
      attendees: 2600,
      banner: "https://www.am.ai/static/caeb54cb7ba4bcb78cf209724f43cb3d/8c557/logo_icml.png",
      contactEmail: "info@renewableenergyconf.com",
    },
    {
      id: 17,
      title: "Data Science & Analytics Forum",
      organizer: "DataInnovators",
      date: "2024-05-25",
      location: "Chicago, IL",
      status: "upcoming",
      attendees: 3400,
      banner: "https://www.am.ai/static/caeb54cb7ba4bcb78cf209724f43cb3d/8c557/logo_icml.png",
      contactEmail: "info@datascienceforum.com",
    },
    {
      id: 18,
      title: "Healthcare & Biotech Summit",
      organizer: "BioHealth Innovators",
      date: "2024-11-10",
      location: "Boston, MA",
      status: "upcoming",
      attendees: 4100,
      banner: "https://www.am.ai/static/caeb54cb7ba4bcb78cf209724f43cb3d/8c557/logo_icml.png",
      contactEmail: "info@biotechsummit.com",
    },
    {
      id: 19,
      title: "Robotics & Automation Expo",
      organizer: "RoboTech",
      date: "2024-07-15",
      location: "Las Vegas, NV",
      status: "upcoming",
      attendees: 4300,
      banner: "https://www.am.ai/static/caeb54cb7ba4bcb78cf209724f43cb3d/8c557/logo_icml.png",
      contactEmail: "info@roboticsexpo.com",
    },
    {
      id: 20,
      title: "Education Technology Conference",
      organizer: "EdTech Innovators",
      date: "2024-03-20",
      location: "Washington, DC",
      status: "upcoming",
      attendees: 2900,
      banner: "https://www.am.ai/static/caeb54cb7ba4bcb78cf209724f43cb3d/8c557/logo_icml.png",
      contactEmail: "info@edtechconference.com",
    },
  ];
  

export {columns, conferences, statusOptions};
